
services:

  webserver_python:
    container_name: geodjango_webserver_prod
    image: geogjango_webserver_prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        - DEV_IMAGE=geogjango_webserver_dev
    command: sh -c "cd hellodjango/ &&  /opt/venv/bin/python /opt/venv/bin/gunicorn hellodjango.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DEBUG
      - DATABASE
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - SQL_ENGINE
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_PORT
    networks:
      - geodjango_project_network_prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - postgis

  postgis:
    postgis/postgis:latest
    container_name: geodjango_postgis_prod
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_DBNAME
      - POSTGRES_PASS
      - POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD
    ports:
      - 54321:5432
    networks:
      - geodjango_project_network_prod
    volumes:
      - geodjango_pg_data:/var/lib/postgresql/data

  nginx:
    build:
      context: docker/nginx
    ports:
      - 1337:80
    depends_on:
      - webserver_python
    networks:
      - geodjango_project_network_prod
    volumes:
      - static_volume:/home/app/web/staticfiles

networks:
  geodjango_project_network_prod:
volumes:
  geodjango_pg_data:
  static_volume:
