
services:
  webserver_python:
    image: geogjango_webserver_dev
    build:
      context: ./docker
      args:
        UBUNTU_BASE_IMAGE: ${UBUNTU_BASE_IMAGE}
    container_name: geodjango_webserver_dev
    command: python3 hellodjango/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgis
    environment:
      - DEBUG
      - DATABASE
      - SECRET_KEY
      - DJANGO_ALLOWED_HOSTS
      - SQL_ENGINE
      - SQL_DATABASE
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_PORT
      - PGDATA
    networks:
      - geodjango_project_network_dev
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
  postgis:
    image: postgis/postgis:latest
    #image: tobi312/rpi-postgresql-postgis:15-3.4-alpine-arm
    container_name: geodjango_postgis_dev
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD
      - PGDATA
    ports:
      - 54321:5432
    networks:
      - geodjango_project_network_dev
    volumes:
      - geodjango_pg_data:${PGDATA}

  redis:
    image: redis:7
    container_name: geodjango_redis_server
    networks:
      - geodjango_project_network_dev

networks:
  geodjango_project_network_dev:
volumes:
  geodjango_pg_data:
