
services:

  webserver_python:
    container_name: geodjango_webserver_prod
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        UBUNTU_BASE_IMAGE: ${UBUNTU_BASE_IMAGE}
    command: sh -c "cd hellodjango/ && gunicorn hellodjango.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env.prod
    networks:
      - geodjango_project_network_prod
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    depends_on:
      - postgis

  postgis:
    image: postgis/postgis:latest
    container_name: geodjango_postgis_prod
    env_file:
      - .env.prod.db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    ports:
      - 54321:5432
    networks:
      - geodjango_project_network_prod
    volumes:
      - geodjango_pg_data:/var/lib/postgresql

  nginx:
    build:
      context: docker/nginx
    ports:
      - 1337:80
    depends_on:
      - webserver_python
    networks:
      - geodjango_project_network_prod
    volumes:
      - static_volume:/home/app/web/staticfiles

networks:
  geodjango_project_network_prod:
volumes:
  geodjango_pg_data:
  static_volume:
