
services:
  webserver_python:
    build:
      context: ./docker
      args:
        UBUNTU_BASE_IMAGE: ${UBUNTU_BASE_IMAGE}
    container_name: geodjango_webserver_dev
    command: python3 hellodjango/manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgis
    networks:
      - geodjango_project_network_dev
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
  postgis:
    image: postgis/postgis:latest
    container_name: geodjango_postgis_dev
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST_AUTH_METHOD
    ports:
      - 54321:5432
    networks:
      - geodjango_project_network_dev
    volumes:
      - geodjango_pg_data:/var/lib/postgresql

  redis:
    image: redis:7
    container_name: geodjango_redis_server
    networks:
      - geodjango_project_network_dev

networks:
  geodjango_project_network_dev:
volumes:
  geodjango_pg_data: